version: "3.7"

services:
  stock:
    image: stock-service
    volumes:
      - ./profiles.yml:/profiles.yml
    ports:
      - 80:8080

  db:
    image: postgres:12
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongo:
    image: mongo:5.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

